import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


export const metadata: Metadata = {
  title: "Huzaifa Iqbal Sindhi — Web Developer & MERN Expert",
  description:
    "I'm Huzaifa Iqbal Sindhi, a full-stack developer from Sindh, Pakistan. I specialize in MERN Stack, WordPress, and SEO — building digital solutions that create real-world impact.",
  keywords: [
    "Huzaifa Iqbal Sindhi Web Developer",
    "Huzaifa Iqbal Sindhi Developer",
    "Huzaifa Iqbal Sindhi Portfolio",
    "MERN Stack Developer",
    "MERN Stack Developer Pakistan",
    "React Developer Huzaifa Iqbal Sindhi",
    "Node.js Developer Huzaifa Iqbal Sindhi",
    "MongoDB Developer Huzaifa Iqbal Sindhi",
    "Express.js Developer Huzaifa Iqbal Sindhi",
    "MERN Stack Expert",
    "Full Stack Developer Huzaifa Iqbal Sindhi",
    "React.js Web Developer",
    "Node.js Web Developer",
    "MongoDB Web Developer",
    "React Node MongoDB Developer",
    "MERN Developer Pakistan",
    "WordPress Developer Huzaifa Iqbal Sindhi",
    "WordPress Expert Huzaifa Iqbal Sindhi",
    "WordPress Developer Pakistan",
    "WordPress Specialist Huzaifa Iqbal Sindhi",
    "MERN Stack Web Development",
    "Full Stack Web Developer Pakistan",
    "MERN Stack Portfolio Huzaifa Iqbal Sindhi",
    "React MongoDB Node.js Developer",
    "MERN Stack Solutions Huzaifa Iqbal Sindhi",
    "React Developer Portfolio",
    "WordPress Developer Portfolio",
    "Web Developer Huzaifa Iqbal Sindhi"
  ],
  authors: [{ name: "Huzaifa Iqbal Sindhi", url: "https://www.huzaifa-iqbal.com/" }],
  creator: "Huzaifa Iqbal Sindhi",
  themeColor: "#C778DD",
  openGraph: {
    title: "Huzaifa Iqbal Sindhi — Full Stack Developer & SEO Expert",
    description:
      "From rural Sindh to digital revolutions — I build fast, SEO-optimized, and beautiful web apps using the latest tech.",
    url: "https://www.huzaifa-iqbal.com/",
    siteName: "Huzaifa Iqbal Sindhi Portfolio",
    images: [
      {
        url: "https://www.huzaifa-iqbal.com/icons/favicon.png",
        width: 1200,
        height: 630,
        alt: "Huzaifa Iqbal Sindhi Portfolio",
      },
    ],
    type: "website",
  }
};



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata:  = {
//   title: "Portfolio",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
