import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


export const metadata: Metadata = {
  title: "Huzaifa Iqbal — Web Developer & MERN Expert",
  description:
    "I'm Huzaifa Iqbal, a full-stack developer from Sindh, Pakistan. I specialize in MERN Stack, WordPress, and SEO — building digital solutions that create real-world impact.",
  keywords: [
    "Huzaifa Iqbal",
    "Web Developer Pakistan",
    "MERN Stack Developer",
    "WordPress Expert",
    "SEO Specialist",
    "Frontend Developer",
    "Next.js Portfolio",
    "React Developer",
    "Developer from Sindh"
  ],
  authors: [{ name: "Huzaifa Iqbal", url: "https://www.huzaifa-iqbal.com/" }],
  creator: "Huzaifa Iqbal",
  themeColor: "#C778DD",
  openGraph: {
    title: "Huzaifa Iqbal — Full Stack Developer & SEO Expert",
    description:
      "From rural Sindh to digital revolutions — I build fast, SEO-optimized, and beautiful web apps using the latest tech.",
    url: "https://www.huzaifa-iqbal.com/",
    siteName: "Huzaifa Iqbal Portfolio",
    images: [
      {
        url: "https://www.huzaifa-iqbal.com/",
        width: 1200,
        height: 630,
        alt: "Huzaifa Iqbal Portfolio",
      },
    ],
    type: "website",
  }
};



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata:  = {
//   title: "Portfolio",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
